version: "3.9"
services:
  db:
    image: postgres:13.4
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    ports:
      - "54333:5432"
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
    name: backend
